repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog3 -p 1 --rules ../custom_config.json .'
        language: system
        stages: ["commit", "push"]